### ISSUE TITLE
`Read` on uninitialized buffer may cause UB (4 functions)

### ISSUE THREAD

**Issue by JOE1994** [otake84/messagepack-rs#2]
Hello :crab:,
we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

## Issue Description

https://github.com/otake84/messagepack-rs/blob/ceaf01318383b00ccc93e95f065b8fd0afcc8d68/messagepack-rs/src/deserializable.rs#L59-L71

https://github.com/otake84/messagepack-rs/blob/ceaf01318383b00ccc93e95f065b8fd0afcc8d68/messagepack-rs/src/deserializable.rs#L90-L92

https://github.com/otake84/messagepack-rs/blob/ceaf01318383b00ccc93e95f065b8fd0afcc8d68/messagepack-rs/src/deserializable.rs#L90-L92

4 functions (`deserializable::Deserializable::{deserialize_string, deserialize_extension_others, deserialize_map::deserialize_string_primitive}`) create an uninitialized buffer and passes it to user-provided `Read` implementation. This is unsound, because it allows safe Rust code to exhibit an undefined behavior (read from uninitialized memory).

[This part](https://doc.rust-lang.org/std/io/trait.Read.html#tymethod.read) from the `Read` trait documentation explains the issue:

> It is your responsibility to make sure that `buf` is initialized before calling `read`. Calling read with an uninitialized `buf` (of the kind one obtains via `MaybeUninit<T>`) is not safe, and can lead to undefined behavior.

## How to fix the issue?

The Naive & safe way to fix the issue is to always zero-initialize a buffer before lending it to a user-provided `Read` implementation. Note that this approach will add runtime performance overhead of zero-initializing the buffer.

As of Jan 2021, there is not yet an ideal fix that works in stable Rust with no performance overhead. Below are links to relevant discussions & suggestions for the fix.

* [Well-written document regarding the issue](https://paper.dropbox.com/doc/IO-Buffer-Initialization-MvytTgjIOTNpJAS6Mvw38)
* [Rust RFC 2930](https://github.com/rust-lang/rfcs/blob/master/text/2930-read-buf.md#summary)
* [nightly feature `std::io::Initializer`](https://doc.rust-lang.org/std/io/struct.Initializer.html)
* [Discussion in Rust Internals Forum](https://internals.rust-lang.org/t/uninitialized-memory/1652)

**Comment by otake84** [comment]
Sorry for the late reply.
I have responded with the following PR.
https://github.com/otake84/messagepack-rs/pull/3
